### ISSUE TITLE
Unable to create tickets (Tags issue when objects are null)

### ISSUE THREAD

**Issue by mathiasmadsen** [BadChoice/handesk#396]
Hi, I believe this is a bug in someway, but since I have only worked with a few Laravel projects before and I have yet to become familiar with Handesk, I am not sure what the right approach would be in order to solve the issue (or whether the problem is only present on my installation).

**Problem**
I am unable to create a ticket / load the page 'tickets/create'. I receive the attached error.
<img width="1173" alt="error" src="https://user-images.githubusercontent.com/3418529/71483413-08c1f600-2808-11ea-816d-61327b444674.png">

**Investigating the issue**
As I have tried to debug the issue, I found that the error might be related to "object" => null in the following script:
`@include('components.js.taggableInput', ["el" => "tags", "endpoint" => "tickets", "object" => null])`

The function seems to work fin if I change that value to something else, e.g.
`@include('components.js.taggableInput', ["el" => "tags", "endpoint" => "tickets", "object" => "null"])`

The same error appear when I create a lead or an idea.

**My local setup**
Handesk (current)
Laravel 5.8
PHP 7.3.7 (w. MAMP 5.4)

**Comment by BadChoice** [comment]
Thanks for the feedback, I believe it should be fixed now (in dev branch)
can you confirm it works?

Thanks!

**Comment by niskah-energies** [comment]
Hi @BadChoice , it's not fixed. I just install and I have the same error.

**Comment by swanback** [comment]
I pulled the dev branch changes from 1/14 and it is now working for me - had the same experience as OP.

**Comment by BadChoice** [comment]
great!
